version: '3.8'

networks:
  net:
    driver: bridge

services:
#TRAEFIK
  traefik:
    image: traefik:latest
    container_name: traefik
    networks:
      - net
    ports:
    - "443:443"
    - "80:80"
    restart: unless-stopped
    volumes:
    - $PWD/data/traefik:/etc/traefik
    - /var/run/docker.sock:/var/run/docker.sock
#AUTHELIA
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: unless-stopped
    networks:
      - net
    volumes:
      - ${PWD}/data/authelia:/config
    environment:
      TZ: "Australia/Perth"
#REDIS
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ${PWD}/data/redis:/data
    networks:
      - net
    restart: unless-stopped
    environment:
      - TZ=Australia/Perth